version: '2'
services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 4567:4567
    environment:
      - GITHUB_BRANCH=master
      - REDIS_URL=redis://redis
    links:
      - redis
  redis:
    image: redis
